name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Get Current Date and Time
        id: get-date-time
        run: echo "current_date_time=$(date '+%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Upload build artifacts
        if: env.is_first_push == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: react-build-artifacts-${{ env.current_date_time }}
          path: build/
          retention-days: 45

      - name: Copy files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/"
          target: "/var/www/html/React-Build-Deploy/"

      - name: SSH into EC2 and restart Apache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart apache2
