name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Determine if first push
        id: check-first-push
        run: |
          git fetch origin main --depth=1
          if [ "$(git rev-list --count HEAD ^origin/main)" -eq 0 ]; then
            echo "is_first_push=true" >> $GITHUB_ENV
          else
            echo "is_first_push=false" >> $GITHUB_ENV
          fi

      - name: Upload build artifacts
        if: env.is_first_push == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: react-build-artifacts-$(date +%Y-%m-%d)
          path: build/
          retention-days: 45

      - name: Copy files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/"
          target: "/var/www/html/React-Build-Deploy/"

      - name: SSH into EC2 and restart Apache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart apache2
